### ISSUE TITLE
Wrong parsing of dates

### ISSUE THREAD

**Issue by wikarg** [lostindark/DriverStoreExplorer#1]
I have Win7 64 bit (Russian version) and got this exception almost on any action (Refresh/Add Store)

************** Exception Text **************
System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at Rapr.Utils.PNPUtil.EnumeratePackages() in C:\Users\Teddy\Source\Repos\DriverStoreExplorer\Rapr\Core\PNPUtilLib\PNPUtil.cs:line 72
   at Rapr.DSEForm.backgroundWorker1_DoWork(Object sender, DoWorkEventArgs e) in C:\Users\Teddy\Source\Repos\DriverStoreExplorer\Rapr\Core\DSEForm.cs:line 153
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Rapr
    Assembly Version: 0.7.0.0
    Win32 Version: 0.7.0.0
    CodeBase: file:///D:/soft/DriverStoreExplorer/Rapr.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.1072
    Win32 Version: 0.7.0.0
    CodeBase: file:///D:/soft/DriverStoreExplorer/Rapr.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by lostindark** [comment]
I don't have a Russian machine and can not test it.
Can you send me the output of pnputil?
 1) Open CMD prompt. 
 2) Run "pnputil -e > %TEMP%\pnputil.txt" 
 3) Send me %TEMP%\pnputil.txt.

**Comment by wikarg** [comment]
Email is marked as "noreply" so i will put this pnputil.txt there :)

--------------
Служебная программа PnP Майкрософт

Опубликованное имя :            
oem0.inf
Поставщик пакета драйвера:   Cisco Systems
Класс:                     Сетевые адаптеры
Дата разработки и версия драйвера :   
02/26/2014 3.1.6019.0
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem1.inf
Поставщик пакета драйвера:   Microsoft
Класс:                     Принтеры
Дата разработки и версия драйвера :   
06/21/2006 6.1.7601.17514
Имя подписавшего :               Microsoft Windows

Опубликованное имя :            
oem2.inf
Поставщик пакета драйвера:   SCM Microsystems Inc.
Класс:                     Контроллеры USB
Дата разработки и версия драйвера :   
01/24/2007 2.01.00.01
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem3.inf
Поставщик пакета драйвера:   SCM Microsystems Inc.
Класс:                     Устройства чтения смарт-карт
Дата разработки и версия драйвера :   
04/25/2007 4.39.00.01
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem4.inf
Поставщик пакета драйвера:   SeriousBit
Класс:                     Сетевая служба
Дата разработки и версия драйвера :   
02/02/2015 3.1.2
Имя подписавшего :               

Опубликованное имя :            
oem5.inf
Поставщик пакета драйвера:   Realtek Semiconductor Corp.
Класс:                     Звуковые, видео и игровые устройства
Дата разработки и версия драйвера :   
06/18/2015 6.0.1.7541
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem6.inf
Поставщик пакета драйвера:   Realtek
Класс:                     Сетевые адаптеры
Дата разработки и версия драйвера :   
12/26/2012 7.067.1226.2012
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem7.inf
Поставщик пакета драйвера:   NT Kernel Resources
Класс:                     Сетевая служба
Дата разработки и версия драйвера :   
02/21/2013 3.0.8.1
Имя подписавшего :               

Опубликованное имя :            
oem8.inf
Поставщик пакета драйвера:   ASUSTek Computer Inc
Класс:                     Контроллеры USB
Дата разработки и версия драйвера :   
03/28/2013 5.30.20.0
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem9.inf
Поставщик пакета драйвера:   ASUSTek Computer Inc
Класс:                     Контроллеры запоминающих устройств
Дата разработки и версия драйвера :   
03/28/2013 5.30.20.0
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem10.inf
Поставщик пакета драйвера:   ASUSTek Computer Inc
Класс:                     Контроллеры USB
Дата разработки и версия драйвера :   
03/28/2013 5.30.20.0
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem11.inf
Поставщик пакета драйвера:   MediaTek Inc.
Класс:                     Порты (COM и LPT)
Дата разработки и версия драйвера :   
01/22/2015 3.0.1504.0
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem20.inf
Поставщик пакета драйвера:   Intel
Класс:                     Контроллеры USB
Дата разработки и версия драйвера :   
07/31/2013 9.4.0.1025
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem12.inf
Поставщик пакета драйвера:   NVIDIA
Класс:                     Видеоадаптеры
Дата разработки и версия драйвера :   
06/02/2016 10.18.13.6839
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem21.inf
Поставщик пакета драйвера:   Intel(R) Corporation
Класс:                     Контроллеры USB
Дата разработки и версия драйвера :   
03/29/2013 2.5.0.19
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem30.inf
Поставщик пакета драйвера:   NVIDIA Corporation
Класс:                     Звуковые, видео и игровые устройства
Дата разработки и версия драйвера :   
05/10/2016 1.3.34.15
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem13.inf
Поставщик пакета драйвера:   NVIDIA Corporation
Класс:                     Звуковые, видео и игровые устройства
Дата разработки и версия драйвера :   
03/24/2016 1.3.34.14
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem22.inf
Поставщик пакета драйвера:   Intel(R) Corporation
Класс:                     Контроллеры USB
Дата разработки и версия драйвера :   
03/29/2013 2.5.0.19
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem14.inf
Поставщик пакета драйвера:   NVIDIA
Класс:                     Контроллеры USB
Дата разработки и версия драйвера :   
03/01/2016 6.14.13.6444
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem23.inf
Поставщик пакета драйвера:   Intel
Класс:                     Системные устройства
Дата разработки и версия драйвера :   
03/29/2013 2.5.0.19
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem15.inf
Поставщик пакета драйвера:   Intel
Класс:                     Системные устройства
Дата разработки и версия драйвера :   
08/19/2013 9.5.14.1724
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem24.inf
Поставщик пакета драйвера:   ASUSTeK Computer Inc.
Класс:                     Системные устройства
Дата разработки и версия драйвера :   
11/08/2012 12.14.17.909
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem42.inf
Поставщик пакета драйвера:   Logitech, Inc.
Класс:                     Звуковые, видео и игровые устройства
Дата разработки и версия драйвера :   
07/09/2014 8.53.0.2
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem16.inf
Поставщик пакета драйвера:   Intel
Класс:                     Системные устройства
Дата разработки и версия драйвера :   
07/25/2013 9.4.0.1023
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem25.inf
Поставщик пакета драйвера:   SteelSeries
Класс:                     Системные устройства
Дата разработки и версия драйвера :   
06/25/2013 2.4.0003.2
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem43.inf
Поставщик пакета драйвера:   Logitech
Класс:                     Неизвестен класс драйвера.
Дата разработки и версия драйвера :   
07/01/2009 3.03.107.0
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem17.inf
Поставщик пакета драйвера:   Intel
Класс:                     IDE ATA/ATAPI контроллеры
Дата разработки и версия драйвера :   
07/25/2013 9.4.0.1023
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem26.inf
Поставщик пакета драйвера:   SteelSeries
Класс:                     Устройства HID (Human Interface Devices)
Дата разработки и версия драйвера :   
06/25/2013 2.4.0003.2
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem35.inf
Поставщик пакета драйвера:   Microsoft
Класс:                     Принтеры
Дата разработки и версия драйвера :   
05/28/2012 15.0.4128.4000
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem44.inf
Поставщик пакета драйвера:   Logitech
Класс:                     Мыши и иные указывающие устройства
Дата разработки и версия драйвера :   
09/24/2014 8.57.00.0
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem18.inf
Поставщик пакета драйвера:   Intel
Класс:                     Системные устройства
Дата разработки и версия драйвера :   
07/25/2013 9.4.0.1023
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem27.inf
Поставщик пакета драйвера:   NVIDIA
Класс:                     Звуковые, видео и игровые устройства
Дата разработки и версия драйвера :   
04/12/2016 1.2.40
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem45.inf
Поставщик пакета драйвера:   Logitech
Класс:                     Устройства HID (Human Interface Devices)
Дата разработки и версия драйвера :   
04/19/2013 8.46.17.1
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem19.inf
Поставщик пакета драйвера:   Intel
Класс:                     Системные устройства
Дата разработки и версия драйвера :   
07/25/2013 9.4.0.1023
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem28.inf
Поставщик пакета драйвера:   NVIDIA
Класс:                     Мыши и иные указывающие устройства
Дата разработки и версия драйвера :   
08/25/2014 8.16.21500.1063
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem46.inf
Поставщик пакета драйвера:   Logitech
Класс:                     Системные устройства
Дата разработки и версия драйвера :   
11/23/2009 3.04.131.0
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem29.inf
Поставщик пакета драйвера:   NVIDIA
Класс:                     Видеоадаптеры
Дата разработки и версия драйвера :   
06/29/2016 10.18.13.6869
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

Опубликованное имя :            
oem47.inf
Поставщик пакета драйвера:   Logitech
Класс:                     Устройства HID (Human Interface Devices)
Дата разработки и версия драйвера :   
11/23/2009 3.04.131.0
Имя подписавшего :               Microsoft Windows Hardware Compatibility Publisher

----------------

**Comment by lostindark** [comment]
Looks like the output gets break into multi lines.
Can you send the actual file to lostindark<at>gmail.com so I can get the line ending correctly?

**Comment by wikarg** [comment]
Sent pnputil.txt by email

**Comment by lostindark** [comment]
Looks like the format is a little different than the one on English OS. The new line makes it much harder to parse. I need to re-write the entire parsing logic and that takes some time.

**Comment by lostindark** [comment]
Rewrite the parsing logic, which actually is more complex than my initial assessment.

Commit: https://github.com/lostindark/DriverStoreExplorer/commit/57ed2682185fdbcdedcf16eeaab0bb05ef93887b

**Comment by wikarg** [comment]
I've tested, and it seems works perfectly (all drivers info loaded correctly).
Thanks!

PS i will close the issue
