### ISSUE TITLE
Allow disabling grouping

### ISSUE THREAD

**Issue by kilrah** [lostindark/DriverStoreExplorer#10]
Now that drivers are grouped by type it has the disadvantage that sorting by column (e.g. Pkg provider) won't bring all drivers with the same values at the same location, they'll still be spread out in the various type groups. Would be good to be able to disable grouping for that purpose so we can more easily see what comes from where.

**Comment by lostindark** [comment]
I found a better way to archive what you need. Now if you click any column, it will automatically group use that column. This is implemented by 2db39a702913e1a944b85041beaff38bdcf69210
