### ISSUE TITLE
Driver scanning task - Add text string (centre) and status text on bottom left

### ISSUE THREAD

**Issue by bovirus** [lostindark/DriverStoreExplorer#100]
@lostindark 

![Driver storage](https://user-images.githubusercontent.com/1262554/80790310-c7af6900-8b8e-11ea-977b-74fe95052aec.jpg)

When the program are scanning for driver driver list theer is text in teh center of window "No items in the list". and on bottom left there is a green line moving with "Ready" indicator.

I believe that these text could be out of context for this operation.

Could be possible to have in this situation (driver scanning) on the center of the window a text like "Driver scanning" and bottom text string "Scanning"?
 
Thanks.

**Comment by lostindark** [comment]
Fixed in ec75e23937a557e8a026b218e7af6f74d5dbf5b4.
