### ISSUE TITLE
GUI - Use of operation parameter in string is not ideal for multilanguage

### ISSUE THREAD

**Issue by bovirus** [lostindark/DriverStoreExplorer#101]
@lostindark 

Use of parameter teat report what kind op operation is selecetd is not ideal for multilanguage

Ex.

data name="Message_Delete_Multiple_Packages"
value = About to {0} {1} packages from driver store.
 
data name="Message_Delete_Result"
value=Deletion of {0} ({1}) {2}.

data name="Message_Delete_Single_Package"
value=About to {0} {1} ({2}) from driver store.

its seems that {0} it's the operation (delete).
BNut if teh string is specfic for deletion why use {0} to build the string instead like

data name="Message_Delete_Single_Package"
value=About to delete {1} ({2}) from driver store.
![Driver storage 02e](https://user-images.githubusercontent.com/1262554/80791118-f4fd1680-8b90-11ea-801e-cf97c5705849.jpg)
![Driver storage 02i](https://user-images.githubusercontent.com/1262554/80791135-faf2f780-8b90-11ea-855a-80e543cc07be.jpg)
![Driver storage 03e](https://user-images.githubusercontent.com/1262554/80791147-00e8d880-8b91-11ea-8c42-2c32bba2b426.jpg)
![Driver storage 03i](https://user-images.githubusercontent.com/1262554/80791152-047c5f80-8b91-11ea-8f13-c99de875795a.jpg)

Fior a better understanding I propose to add a CR/LF before "Are you sure?"

Thanks.

**Comment by lostindark** [comment]
Fixed in 424bf1acbbbbc10bdcf72a4b1e47a851c7d82d50.
