### ISSUE TITLE
Windows Installer Explorer

### ISSUE THREAD

**Issue by informatorius** [lostindark/DriverStoreExplorer#105]
Would it be possible to also make a Windows Installer Explorer? So I can remove old Installer files from Windows C:\Windows\Installer and C:\ProgramData\Package Cache

I found a tool whitch lists the content https://www.nirsoft.net/utils/installed_packages_view.html

But it cannot delete the items.

**Comment by lostindark** [comment]
AFAIK, remove installer files will cause problem for when those app needs to update/repair, and are not recommended.
I don't have enough knowledge about the windows installer, and don't know how to track the unused/un-needed one.

**Comment by MagicAndre1981** [comment]
Data are stored here:

HKEY_CLASSES_ROOT\Installer\Products

so check for files in C:\Windows\Installer which are not present in any key in registry.

**Comment by informatorius** [comment]
Found a workaround for get more free space on C:\ by just moving Windows Installer and PackageCache to a different drive and then create a hard link junction to them.
