### ISSUE TITLE
v0.10.58 Unable to find entry point named 'DiUninstallDriver' in DLL 'newdev.dll'

### ISSUE THREAD

**Issue by Tha14** [lostindark/DriverStoreExplorer#106]
Hello,
Been using this tool for a very long time and this is the first time I encounter an error when uninstalling an old driver.
The driver I am having an issue with is 'nv_dispi.inf' version 26.21.14.4120 and it was installed when I was using a different GPU form the one I am using right now. I've just upgraded the nvidia driver to the latest version but I am getting this error now when attempting to force uninstall: 
![Screenshot_1](https://user-images.githubusercontent.com/5931740/85908308-433f3680-b81d-11ea-9191-96b424a63fa0.png)
"Unable to find entry point named 'DiUninstallDriver' in DLL 'newdev.dll'"

I checked and the system is currently using the latest nvidia driver and not the one I am trying to delete.
Please look into this. Thank you

Quick Edit: I forgot to include that uninstalling the old GPU + driver from device manager successfully uninstalled everything.

**Comment by lostindark** [comment]
What is your OS version?

**Comment by Tha14** [comment]
> 
> 
> What is your OS version?

Windows 10 1607

**Comment by lostindark** [comment]
Looks like the DiUninstallDriver is not available on your OS version, I'll find a support function to replace it.

**Comment by Tha14** [comment]
Sounds great. Thanks.

**Comment by lostindark** [comment]
I've stop calling DiUninstallDriver when the OS doesn't support it in 44c3eec965a57b5ea26fb26d8c15d9bc4f8279ef. This means for this OS, the driver will be force uninstalled, but the device is leaving at using a non-exist not working driver. You'll probably need to manually fix it (or OS may fix it itself).

I'll look into a better proper fix later, which will take more time.

**Comment by Tha14** [comment]
> 
> 
> I've stop calling DiUninstallDriver when the OS doesn't support it in [44c3eec](https://github.com/lostindark/DriverStoreExplorer/commit/44c3eec965a57b5ea26fb26d8c15d9bc4f8279ef). This means for this OS, the driver will be force uninstalled, but the device is leaving at using a non-exist not working driver. You'll probably need to manually fix it (or OS may fix it itself).
> 
> I'll look into a better proper fix later, which will take more time.

Time is not an issue. I am only using the tool to remove older versions of drivers, If I am permanently removing a driver I am doing it through device manager.

**Comment by lostindark** [comment]
Close the issue for now.
