### ISSUE TITLE
Incorrect file size report?

### ISSUE THREAD

**Issue by pstrg** [lostindark/DriverStoreExplorer#107]
It caught my attention that a file (nova10.inf) appeared in two identical entries except for size (15MB and 10MB).
Looking further, I noted that the two files, located in different folders, are reported by Explorer as much smaller (just 2K).
It seems that there may be a bug.

![possible_error](https://user-images.githubusercontent.com/13485213/88981723-fd9edf00-d29c-11ea-96a4-1dd95f68b832.jpg)

**Comment by sylveon** [comment]
Driver store explorer also includes the dependencies in the file size calculation (the amd64 and i386 folders)

**Comment by lostindark** [comment]
As @sylveon explained above, this is by design.
