### ISSUE TITLE
Compile - Instruction to compile source code

### ISSUE THREAD

**Issue by bovirus** [lostindark/DriverStoreExplorer#109]
@lostindark 

Could you please provide some instructions (that you can add to RAEDME) about

- requirements to compile source code
- Instruction how to compile source code

Thanks.

**Comment by sylveon** [comment]
Open the solution in visual studio and hit build

**Comment by bovirus** [comment]
@sylveon

I  did it (with SV2017) and I got a lot of errors.

Now  I repopen .sln project and build is ok.

**Comment by lostindark** [comment]
My personal environment is VS 2019. Haven't test against VS 2017 for a while and maybe some latest code didn't work on it.

**Comment by bovirus** [comment]
OK, Thanks.

I propose to add this info (use VS2019 ) in README.
