### ISSUE TITLE
About not working with v0.11.13

### ISSUE THREAD

**Issue by DrFeelNice** [lostindark/DriverStoreExplorer#113]
Hi,

![2020-08-07_055920](https://user-images.githubusercontent.com/51505681/89607681-62e16a00-d873-11ea-9b9c-4424ddcabb28.png)

With Windows 7 Pro 64bits

Regards,

**Comment by lostindark** [comment]
Do you see the same issue with v0.10.58?

**Comment by DrFeelNice** [comment]
No, old version is working fine !

**Comment by DrFeelNice** [comment]
OK Teddy, I've found the problem occurs with my firewall.
Your new version requires an Internet access...

**Comment by lostindark** [comment]
There is an issue with the new build, it didn't handle the network error correctly. I've fixed it in b18e954fc8b00dbcd3c535592e0fa7c1bf041d6b.
