### ISSUE TITLE
False positive with 0.11.20

### ISSUE THREAD

**Issue by DrFeelNice** [lostindark/DriverStoreExplorer#115]
Hello Teddy,

Are you aware of that :
https://www.virustotal.com/gui/file/b8e8fffcc06f61946860e4e1a7534076750f131a416cfa216045a5f1fc1fd318/detection

**Comment by lostindark** [comment]
It was showing detected as virus by Microsoft & Rising. I clicked re-analyze and "Microsoft" is now green.
I'm pretty sure this is false positive. But it is hard to get the Anti-Virus company to fix their stuff.

The releases are directly build and published by appveyor. Their environment should be safe. If people have concern, they can always took the source code and build themselves.

**Comment by lostindark** [comment]
Now all shows green (except one shows unknown).
