### ISSUE TITLE
Driver store Explorer v 0.11.20 crashes on win7

### ISSUE THREAD

**Issue by jvidalw** [lostindark/DriverStoreExplorer#118]
Well, the title pretty much sums it up.
version 0.11.20 crashes under Win7 x64. Works on win8.1 and win10
Forgot to mention, it crashes immediately after double clicking the exe. It won't even open.

Version 0.11.18 works.

I hope you can fix it

PS:

These errors appear in the event viewer:

first one, id: 1026, origin ".net framework":
Aplicación: Rapr.exe
Versión de Framework: v4.0.30319
Descripción: el proceso terminó debido a una excepción no controlada.
Información de la excepción: System.Configuration.ConfigurationErrorsException
   en System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   en System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   en System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Información de la excepción: System.Configuration.ConfigurationErrorsException
   en System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   en System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   en System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   en System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   en System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   en System.Configuration.ConfigurationManager.GetSection(System.String)
   en System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   en System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   en System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   en System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   en System.Configuration.SettingsBase.get_Item(System.String)
   en System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   en System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   en Rapr.Properties.Settings.get_UpgradeRequired()
   en Rapr.Program.Main()

second one, id:1000, origin "Application Error":

Nombre de la aplicación con errores: Rapr.exe, versión: 0.11.20.0, marca de tiempo: 0x5f362a5e
Nombre del módulo con errores: KERNELBASE.dll, versión: 6.1.7601.24545, marca de tiempo: 0x5e0eb6bd
Código de excepción: 0xe0434352
Desplazamiento de errores: 0x000000000000b87d
Id. del proceso con errores: 0x218c
Hora de inicio de la aplicación con errores: 0x01d6751ee6fbd83b
Ruta de acceso de la aplicación con errores: C:\Util\Rapr.exe
Ruta de acceso del módulo con errores: C:\Windows\system32\KERNELBASE.dll
Id. del informe: 24b2f884-e112-11ea-8f77-005056c00008

hope it helps.

**Comment by lostindark** [comment]
Can you provide Rapr.log? It is usually in the same folder as the Rapr.exe.

**Comment by jvidalw** [comment]
I updated my original post with info from the windows event viewer. Let me look for the log file.
Unfortunately, there is no log in the same folder as rapr.exe

**Comment by jvidalw** [comment]
Never mind, I found the problem.
When rapr.exe.config is missing, it crashes.
Strangely, previous versions worked without that file...

**Comment by lostindark** [comment]
The rapr.exe.config contains some important info (like userSettings, log listener settings) for the app to run correctly.
If there is a user.config file in the system, but there is no rapr.exe.config, the app don't know how to handle the settings, so it crashed.

If the app was first started without the rapr.exe.config, the user.config will be created with the userSettings, so the app can continue run without the rapr.exe.config.

**Comment by jvidalw** [comment]
I get it, but why it crashes only on win7 if the config file is missing and not on win81/10?
And, like I said, previous versions worked just fine without the file...strange.

**Comment by lostindark** [comment]
The app will crash when it meets all the following condition:
1. No rapr.exe.config
2. user.config exists and there is no userSettings configSections.

So if you've run DSE with rapr.exe.config in the system the first time, it will generate a user.config without userSEttings configSections.
If you run DSE without rapr.exe.config in the system the first time, it will generate a user.config with userSettings configSections.

It totally depends on how you run DSE the first time with that system.

**Comment by jvidalw** [comment]
funny thing is had never run it with rapr.exe.config before (previous versions) in any OS and it always worked, and v.0.11.20 worked on win81/10, but not on win7. I run it from the same folder on the three OSes...
Anyway, besides the mystery, it's not really important, since I am able to run it now.
thanks for your time!

**Comment by lostindark** [comment]
The app settings system is not designed to use without the exe.config. I'm closing this issue.
