### ISSUE TITLE
Release 0.11.26 marked as virus

### ISSUE THREAD

**Issue by oduis** [lostindark/DriverStoreExplorer#122]
By Windows Defender. It should contain Trojan:Win32/Emali.A!cl

**Comment by grimson73** [comment]
> By Windows Defender. It should contain Trojan:Win32/Emali.A!cl

Same!

**Comment by j0taDasFestas** [comment]
> By Windows Defender. It should contain Trojan:Win32/Emali.A!cl

yes i was downloading it today and WD marked has trojan maybe false-positive lets wait to see

**Comment by lostindark** [comment]
I've submit a false positive report to Microsoft. Waiting for response.

**Comment by lostindark** [comment]
Haven't got a response yet. But virtual total shows that Windows Defender is clear now.
