### ISSUE TITLE
Request: Add and Extract drivers from Offline systems

### ISSUE THREAD

**Issue by Corsten56** [lostindark/DriverStoreExplorer#13]
Hello.

Can you add ability to add and extract drivers from Offline systems?
I've searched whole web and don't found this functionality.

**Comment by lostindark** [comment]
Currently there is no plan for this.
Contribution is welcome.

**Comment by scottcopus** [comment]
I vote for this too. Being able to do driver management to an offline DISM-mounted image (WIM) would be a nice feature.

**Comment by lostindark** [comment]
v0.10.3 is released to include support for offline driver store.
https://github.com/lostindark/DriverStoreExplorer/releases/tag/v0.10.3
