### ISSUE TITLE
Intel drivers from 1968

### ISSUE THREAD

**Issue by pingmusic** [lostindark/DriverStoreExplorer#134]
![intel](https://user-images.githubusercontent.com/46450770/95063089-d7803a00-0738-11eb-98ac-3723cbbfb478.png)

Intel drivers from 1968 get the highest ranking when Microsoft Update looks 

"Select Old Driver" 1968 drivers default uncheck need...

**Comment by lostindark** [comment]
This is an issue of Intel. They published drivers using very old date (not sure exactly why).
What do you expect from this tool?

**Comment by pingmusic** [comment]
Pleased to meet you ^^
"Select Old Driver(s)" add system device Intel drivers in the exclusion

**Comment by lostindark** [comment]
How do you define a system device driver? We need a proper definition before we find the right way to exclude them.

**Comment by lostindark** [comment]
I've excluded boot critical drivers from "Select Old Driver(s)" in 112910238c4220f199a7d8af64e40c39d382b627.
