### ISSUE TITLE
"OK" and "Cancel" buttons in the Choose Driver Store dialog are not localized

### ISSUE THREAD

**Issue by ItielMaN** [lostindark/DriverStoreExplorer#137]
![תמונה](https://user-images.githubusercontent.com/18016656/97607115-42135580-1a19-11eb-8d31-0d199d64871b.png)

This is with the Hebrew locale which is 100% translated in the lang file. I see the same in other languages.

**Comment by lostindark** [comment]
Fixed in 55c6c4602226e8d6644f27db642f1651e1f5e2e7.
