### ISSUE TITLE
serious problem

### ISSUE THREAD

**Issue by Johnsen2021** [lostindark/DriverStoreExplorer#156]
Your program is good, but it would be PERFECT if you could permanently uninstall (ALL) adapter drivers !!!!! such as:
Audio, video controller
Graphics cards
IDE ATA / ATAPI SATA controller
wireless and ethernet adapters
ALL drive controllers
Modems
Monitors
Network adapter
Processors
storage controller

THANK YOU VERY MUCH FOR YOUR EFFORTS TO MAKE THIS WONDERFUL SOFTWARE PERFECT.

Have a nice day

Nemerino Serunkastini

**Comment by lostindark** [comment]
If you want to uninstall all thirdparty driver, just select all and choose delete.

**Comment by Johnsen2021** [comment]
That's the problem - NOT ALL drivers for the entire hardware are displayed

Teddy Z <notifications@github.com> schrieb am Fr., 12. Feb. 2021, 19:37:

**Comment by lostindark** [comment]
The tool only list third party drivers. This is by design.
You should not delete inbox drivers (those come with Windows). Those are critical for the system to work correctly. Delete wrong ones incorrect can cause serious system issue (not booting, not functioning) and hard to fix.

**Comment by Johnsen2021** [comment]
Hello,

strange, I installed third party network driver and it was NOT installed
!!!!!.  Your ingenious software has great potential, but you castrate it
too much !!!!!!.  October that's nice that you think about crashes and so
on that's SUPER, but you should be able to see graphics drivers, network
drivers and finally delete them completely.

Best Regards

Nemerino Serunkastini


Teddy Z <notifications@github.com> schrieb am Sa., 13. Feb. 2021, 22:13:
