### ISSUE TITLE
Multilanguage version

### ISSUE THREAD

**Issue by bovirus** [lostindark/DriverStoreExplorer#16]
Could be possible to add the option to make the software multi-language?

**Comment by CHEF-KOCH** [comment]
I don't see the reason .. it's not like this utility provide much dialogs.

**Comment by bovirus** [comment]
Simple: because not all people know English.
And I didn't see the reason why you don't want to implement it.
If you want to encourage the use of this software the multi-language interface encourage (not limit) the use  of the app.
Similar project like this (for development) is Microsoft Windows ISO Downloader that has a simple multi-language interface.

**Comment by CHEF-KOCH** [comment]
The driver files are in english too. Sorry but if someone not know basics like 'refresh' .. 'old', 'drivers' or 'install'/'delete' then he should't mess at all with this tool.

**Comment by lostindark** [comment]
Having multi language support is good. But I don't see a strong need for this given the simplicity of the tool. Also, add the multi language support and have correct translation is not simple.

I'm consider this is a low priority item. It'll be great if somebody want to contribute on this.

**Comment by newmediadev** [comment]
I've just branched a copy of the source and have made a start on creating resource bundles and providing the ability to change languages once the app is loaded.

Here's a screenshot of my work in progress...

![french](https://user-images.githubusercontent.com/447138/46479158-61ae0480-c7e6-11e8-825e-94a253070b33.png)

Once I have a full English resource bundle then the it's just a case of adding and building in support for more languages as time goes by.

**Comment by lostindark** [comment]
Thanks @newmediadev.
