### ISSUE TITLE
[REQUEST] Print drivers list

### ISSUE THREAD

**Issue by Hexaae** [lostindark/DriverStoreExplorer#161]
Can you add an option to print current list of drivers only in a text/csv file? Possibly ordered as you do in the listview.
(Or am I missing a feature it's already implemented maybe?)

**Comment by Hexaae** [comment]
Oh just realized menu function "Esporta" in ITA does this, but should be better to rename it "Esporta lista" or users will think it's to export selected drivers (since there is also another menu item "Esporta tutti i driver")

**Comment by lostindark** [comment]
Looks like it is a translation issue. You can contribute the fix to it.

For now, it only supports export all drivers. Export selected driver is not implemented yet.
