### ISSUE TITLE
Unable to load drivers from the store.

### ISSUE THREAD

**Issue by Galoal** [lostindark/DriverStoreExplorer#163]
I have no idea what this means. When choosing C:/ as my Offline Driver Store it gives the same error.

![image](https://user-images.githubusercontent.com/26205050/115778596-252a6000-a374-11eb-8249-a375a976db2a.png)

**Comment by lostindark** [comment]
Can you share the log file?

**Comment by Galoal** [comment]
Sure, is this it ?

[Rapr.log](https://github.com/lostindark/DriverStoreExplorer/files/6362972/Rapr.log)

**Comment by lostindark** [comment]
Seems like your OS have some issues.
Try:
sfc /scannnow
DISM /Online /Cleanup-Image /RestoreHealth

**Comment by Galoal** [comment]
Both of those commands, on an admin-privileged cmd, gave me an error. My win10 has been presenting issues with not being able to update. Maybe that's the problem.
