### ISSUE TITLE
Windows Update Automatically Restores Deleted Old Drivers

### ISSUE THREAD

**Issue by GitAlexToTheGreek** [lostindark/DriverStoreExplorer#169]
Hi there, 

DSE v0.11.72.0
Windows 10 Home, v21H1

After a scan, these two old drivers are identified:
<a href="https://imgur.com/tRyaazP"><img src="https://i.imgur.com/tRyaazP.png" title="source: imgur.com" /></a>

With "Force Deletion" enabled, they're removed...
<a href="https://imgur.com/DdRLppt"><img src="https://i.imgur.com/DdRLppt.png" title="source: imgur.com" /></a>

(And confirming that the most recent version of the driver is already  installed):
<a href="https://imgur.com/kQKc9SP"><img src="https://i.imgur.com/kQKc9SP.png" title="source: imgur.com" /></a>

Following a system restart, Windows Update automatically restores those deleted files...
<a href="https://imgur.com/XWAZcYf"><img src="https://i.imgur.com/XWAZcYf.png" title="source: imgur.com" /></a>

And as expected, they're back in DSE:
<a href="https://imgur.com/Fr6jHYU"><img src="https://i.imgur.com/Fr6jHYU.png" title="source: imgur.com" /></a>

-> Can anyone advise on how to resolve this loop and effectively clear the outdated files?

Thanks in advance.

**Comment by sylveon** [comment]
Leave them here, and install the new driver. Windows Update will stop trying to install the old drivers that way.

**Comment by GitAlexToTheGreek** [comment]
> Leave them here, and install the new driver. Windows Update will stop trying to install the old drivers that way.



> (And confirming that the most recent version of the driver is already installed):
> [![](https://camo.githubusercontent.com/9c71440365d76b25111d68ad59ffbd1f97fb8bbae327ae2122ef2c292034b972/68747470733a2f2f692e696d6775722e636f6d2f6b514b633953502e706e67)](https://imgur.com/kQKc9SP)

So impossible to remove the old files? Isn't that the objective of this software?

**Comment by sylveon** [comment]
You can remove the ones that WU isn't trying to reinstall.

**Comment by nkh0472** [comment]
> So impossible to remove the old files? Isn't that the objective of this software?

Of course, you can remove it with DSE. Of course, windows will insist on reinstalling it. This can be said to be a bug of Windows (or a feature). :)

**Comment by nkh0472** [comment]
I don't know what logic windows judges the driver needs to be updated. As we all know, there are often some specific release dates for Intel driver updates: 07 / 18 / 1968, 1 / 1 / 1970 and 6 / 21 / 2006, which can be explained as [Microsoft's intention for compatibility](https://www.tenforums.com/windows-updates-activation/175292-what-1970-intel-update-showing-my-list.html).

However, I have also observed that for my Intel Core graphics driver, sometimes after installing the latest driver package, Microsoft insists on installing an older version with version number and release date, and makes the new driver package disabled, which is very puzzling.

For the solution of this kind of problem, you can [use group policy to disable the automatic driver update of specific devices](https://www.howtogeek.com/263851/how-to-prevent-windows-from-automatically-updating-specific-drivers/). However, it seems that group policy is only on the edition above Windows Professional Edition.
