### ISSUE TITLE
Exception from HRESULT: 0xC0040009

### ISSUE THREAD

**Issue by Galamooth** [lostindark/DriverStoreExplorer#171]
After the update of. Net framework throws me an error when scanning the driver store.

Exception from HRESULT: 0xC0040009

I found this.

 Incorrect% WINDIR% \ logs access permissions were the source of this problem. Not related to DSE itself. Anyone have any ideas for solution ????

**Comment by lostindark** [comment]
If the permission for that folder is screwed up, you can update it to just inherit the parent folder permission.
