### ISSUE TITLE
Computer can not start any more after I force deleted😢

### ISSUE THREAD

**Issue by xmaxance** [lostindark/DriverStoreExplorer#173]
How can I do？

**Comment by xmaxance** [comment]
Oh,well after I unplugged my portable storage and it restarted successfully ，is that a bug or anything else?

**Comment by sick13** [comment]
don't force delete drivers that are in use,how do you know witch drivers are safe do delete? DuckDuckGo is your friend...do a bit of research before you go on a rampage deleting stuff

**Comment by xmaxance** [comment]
> don't force delete drivers that are in use,how do you know witch drivers are safe do delete? DuckDuckGo is your friend...do a bit of research before you go on a rampage deleting stuff

Thanks for your help:)
