### ISSUE TITLE
Unified approach to Rapr.log and user.config files locations

### ISSUE THREAD

**Issue by avtneyney** [lostindark/DriverStoreExplorer#175]
I think both of these files should be handled in a similar manner. By default Rapr could store both of them in %LocalAppData%\Rapr (as it is now with "user.config" file) but if you have either of them located in .\ (working directory) then it would use these for a true portable experience.

**Comment by lostindark** [comment]
Unfortunately the .Net configuration system doesn't provide path customization, and I can't move user.config to working directory easily.

**Comment by avtneyney** [comment]
I see. Hope this system gets expanded sometime in the future or maybe there will be something else that will make you to move away from it.
