### ISSUE TITLE
Remove mandatory successful UAC elevation request on startup

### ISSUE THREAD

**Issue by avtneyney** [lostindark/DriverStoreExplorer#176]
Right now Rapr requires a UAC elevation just to launch even if I don't want to inspect active system's driver store which is kind of pointless and not that safe too. At least the application should be able to start with failed elevation and maybe even list something on the local system's driver store it can list without elevated access. Or just let the user to pick an location for an offline driver store right away.

**Comment by lostindark** [comment]
Currently this tool is using DISM API which requires admin permissions even for offline driver store.
