### ISSUE TITLE
Why are the Driver Entries found in AUTORUNS not Displayed in DriverStoreExplorer??

### ISSUE THREAD

**Issue by JazzyJazzjazzy** [lostindark/DriverStoreExplorer#178]
Why are the Driver Entries found in AUTORUNS not Displayed in DriverStoreExplorer??

I should explain that SOME of the drivers appear in DriverStoreExplorer, but not ALL of them appear. 

The Drivers that do not appear seem to be the OLDER Drivers that Windows is apparently not using currently.

I want to UNINSTALL some of these old drivers and I am hopeful that  I can uninstall them using DriverStoreExplorer.

Thank You.

**Comment by JazzyJazzjazzy** [comment]
Apologies, I should explain that SOME of the drivers appear in DriverStoreExplorer, but not ALL of them appear.

**Comment by lostindark** [comment]
DriverStoreExplorer only display third party driver entries. The drivers came with windows are not listed.

**Comment by JazzyJazzjazzy** [comment]
megasas35i.inf
megasas2i.inf
3ware.inf

The above drivers are third party drivers that are not displayed in DSE. There are numerous others that DSE does not find. Suggestions? Thank you.
