### ISSUE TITLE
Two malware engines reported malcious code?

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [lostindark/DriverStoreExplorer#19]
TrendMicro-HouseCall - Suspicious_GEN.F47V0410

Rising - Malware.Undefined!8.C (cloud:jbPekpO0uIO)  

https://www.virustotal.com/en/file/a63b0e8c9d264867a85b823ff3f7b78b549824ab25dfd3d4bfea38a02450539d/analysis/1497073265/

**Comment by lostindark** [comment]
Not sure how you submit the scan, but below is the result for the latest version: https://www.virustotal.com/en/url/73c6e47e8782666bbd59412c298db505d2de575bb469830fbf0032410237f965/analysis/1497073462/

**Comment by lostindark** [comment]
Update: seems the file result inside the scan shows the same:
https://www.virustotal.com/en/file/e3a5bef36d10436980e0a6cd820a0632655441b4cd8ae3e07dea89418af7a029/analysis/1497003131/

My guess is this is a false alarm with these 2 malware engine (since this tool deal with driver store).
You can check the source code of the tool, or decompile the actual exe to check what the tool is doing.

**Comment by lostindark** [comment]
The interesting part is the older version 0.8.2 doesn't suffer from this.
https://www.virustotal.com/en/file/d2c67a6118313171e427232e27d6f8ef1e5bb1d205dc6745faa34d8dd927a70b/analysis/1497073942/

The only change I made is the icon. so I upload the icon for scanning, which shows ok.
https://www.virustotal.com/en/file/a8a4f00a773a1f42f2fca5a50e9df2ef266237ae08eadb9ff4c7d598fa1dea67/analysis/1497074075/

Not sure what actually trigger this.

**Comment by Vulgaris-Viridis** [comment]
If an icon is the only change, it is indeed a strange behavior...  Not sure how their algorithms work, but I'd expect them to be able to tell apart malware from a simple icon... Very strange...

**Comment by lostindark** [comment]
I just publish a new version 0.8.4 and the scan shows no virus.
https://www.virustotal.com/en/file/3a3bcd441b5ed3d7a78157e5e71f9432c3d1a711f3d8a16778b1c4fe2297dd99/analysis/1498791981/
I think this is a false alarm for that 2 antivirus software. Given the new version is OK, I'm close this issue.

**Comment by Vulgaris-Viridis** [comment]
You probably scanned the archive again, when you scan the extracted files it shows malware in the 0.8.4 version as well. 

https://www.virustotal.com/en/file/4a3f3f9fa2ef9c657d47665f1df2a87b77f6048b949ea7d01f452714c3421d27/analysis/1498873124/

Honestly, I'm pretty confident this is a false positive, though it would be great if you could pinpoint the issue so that the other users don't get discouraged when their av engine alerts them...

**Comment by lostindark** [comment]
If you look at the latest report, it is OK.
https://www.virustotal.com/en/file/4a3f3f9fa2ef9c657d47665f1df2a87b77f6048b949ea7d01f452714c3421d27/analysis/

I don't see much I can do here. If it happens again, I may need to contact the antivirus software which has the false positive reports.
