### ISSUE TITLE
Product_About_Title Bug

### ISSUE THREAD

**Issue by luki1412** [lostindark/DriverStoreExplorer#191]
Language string **Product_About_Title** uses **Product_Name** from the English language file so it's never the translated one within the same file. In the image below, **Product_About_Title** is equal to **{0}** and **Product_Name** is equal to **Prehliadač úložiska ovládačov**
![product name](https://user-images.githubusercontent.com/20016096/170992251-ad957286-ebc5-4f2f-b473-35c0d7c908a5.png)

PS: Im not going to translate the title of the program in my translation but I wanted to let you know about the bug.

**Comment by lostindark** [comment]
Fixed in 6e1b3750ced8ccdd3bcb5e688bc5e863316b1f5b.
