### ISSUE TITLE
Driver Store Explorer didn't Select 2 old drivers

### ISSUE THREAD

**Issue by FFreestyleRR** [lostindark/DriverStoreExplorer#195]
Hi,

Driver Store Explorer missed selecting the following **two drivers** when used the **Select Old Driver(s)**:

**ICCWDT.inf** - **11.7.0.1004** when I installed **11.7.0.1005** from the latest intel XTU utility:

https://www.intel.com/content/www/us/en/download/17881/intel-extreme-tuning-utility-intel-xtu.html

Also, when installed the latest nVidia driver 516.59 it seems to install (472.98) as well even when clean install was selected.

It seems it's no longer needed for newer GPUs:

https://www.nvidia.com/download/driverResults.aspx/186164/

516.59 also installed an older version of nvhda.inf (1.3.38.4) along with the latest one (1.3.39.3) which was selected by RAPR correctly.

So I had to check the ICCWDT.inf and the nvmd.inf manually. Maybe because the latest nVidia driver is using the name nvmdig.inf instead of nvmd.inf it wasn't selected.

Can you check these issues and fix them if needed in the next build of the tool?

Thanks and keep up the good work!

**Comment by lostindark** [comment]
Unfortunately the "select old drivers" is a best effort operation. If the inf name changed, I don't have a reliable way of determine whether they're the same driver or not.
Let me know if you have other ideas.

**Comment by FFreestyleRR** [comment]
Hi,

I understand. Yeah, in case where the driver name is changed probably you can't do much about it, but for the ICCWDT.inf it was the same and despite that it wasn't selected by the "select old drivers" at least on my system.

Thanks for the reply and keep the good work.
