### ISSUE TITLE
Problem creating csv file

### ISSUE THREAD

**Issue by amarisd** [lostindark/DriverStoreExplorer#20]
I am trying to run rapr on Win7 sp1;

when selecting all items and requesting export, I get the message:

Export failed: Object reference not set to an instance of an object

I'd appreciate any help to resolve this.

Thanks,

Amari

here's a screenshot 
![screenhunter_42 jun 30 11 06](https://user-images.githubusercontent.com/29803000/27748390-260a2d96-5d84-11e7-8017-7326f2376b68.jpg)

**Comment by lostindark** [comment]
Can you click "View Logs" in the status bar and share the logs here?

**Comment by amarisd** [comment]
Here you go.  This was just after trying to export a csv file a few moments ago.  I had to rename the log file to a txt in order for it to be accepted as an attachment
[Rapr.txt](https://github.com/lostindark/DriverStoreExplorer/files/1116450/Rapr.txt)

**Comment by lostindark** [comment]
Hmmm, the log file doesn't contains any useful information.
What is your detail repro step? I can't repro from my side.

**Comment by amarisd** [comment]
Steps were as follows"
After window was populated with drivers
1.Right clicked and chose Select All
2, Right clicked again and chose Export
3. In File Dialog, selected folder (in my case Desktop) and assigned filename.  Clicked on Save command button.
4. Result was error message.

It did create a csv but showing only 15 of the 80 installed drivers (see attachment which I had to rename from csv to txt.)

[d.txt](https://github.com/lostindark/DriverStoreExplorer/files/1116708/d.txt)

**Comment by lostindark** [comment]
My guess is some drivers have missing information. I've made a change to fix it. Please try this attached file and let me know if it works for you.

**Comment by amarisd** [comment]
That worked beautifully.  thanks for taking the time to solve the problem.  I can't believe I'm the only one who experienced it.
