### ISSUE TITLE
No .exe file

### ISSUE THREAD

**Issue by CompadreTortilla** [lostindark/DriverStoreExplorer#200]
I downloaded this cause my audio is fucked, and I need to delete sonic audio. But when I opened the file for this I realized that there's no .exe so I can't even launch the app.

**Comment by JonnyTech** [comment]
Unzip https://github.com/lostindark/DriverStoreExplorer/releases/download/v0.11.79/DriverStoreExplorer.v0.11.79.zip and double click `rapr.exe`
