### ISSUE TITLE
documentation about gray items

### ISSUE THREAD

**Issue by SynapseScribe** [lostindark/DriverStoreExplorer#231]
Is there any documentation for this tool? For eg. i can't figure out what gray items mean ?

![image](https://github.com/lostindark/DriverStoreExplorer/assets/7840350/b3f814de-1175-439d-b41e-29ff77cd4080)

**Comment by lostindark** [comment]
That's a device that is used to on your system but no longer there. E.g. an USB device that was plugged in previously.
If you're sure that you no longer need it, you can delete the drivers. If you use the device again, the drivers needs to be re-installed if you choose to delete it.
