### ISSUE TITLE
Delay sound

### ISSUE THREAD

**Issue by mazo12321** [lostindark/DriverStoreExplorer#236]
Hello, i installed driver and when i go for example in game i have delay like 0.5-1 sec sound. Also like echo. But when i go to sound control panel -> then select speaker then properties then Advanced i have 3 cards Default format, exclusive mode and Signal Enchancements. When i go to Signal Enchancement there is "Enable audio enchancements" enabled, when i disable that i dont have delay but i my audio is not loud enough with disabled that. So is it possible to fix it? If i go enable audio enchancements how can i fix delay? Thanks!

**Comment by lostindark** [comment]
Not related to DriverExplorer.
