### ISSUE TITLE
Strange behave in Rapr.exe has been found on the result of virustotal's scanning.

### ISSUE THREAD

**Issue by yufeiying** [lostindark/DriverStoreExplorer#24]
Hi, dev,

I downloaded the latest version of DriverStoreExplorer which the version is 0.8.41 form GitHub. Before I ran it, I uploaded the binary file Rapr.exe, which the hash of the file is 7435a4197e3b7c87a4dff26a9627473ae9356179abfe4a47a8664fc36565c1a8, to VirusTotal for scanning. The result showed that there was a strange behave which was a dns lookup for the domain vboxsvr[.]ovh[.]net in this binary file. 

You can check the result here at the bottom of the "file detail": 
https://www.virustotal.com/zh-cn/file/7435a4197e3b7c87a4dff26a9627473ae9356179abfe4a47a8664fc36565c1a8/analysis/1505868168/

I thought it was very strange. So I downloaded the source code and tried to compile by my self. Then I  used VisualStudio 2017 community version to rebuild this project and then I got a new Rapr.exe file which the hash of the file is af44f233166756fb20531f88e10eead5fcc245f5a45b5d80067f632eb52d7e78. And then I uploaded the new file to VirusTotal for scanning, there was no such behave of dns lookup for the strange domain.

You can check the result of my new-built exe here:
https://www.virustotal.com/zh-cn/file/af44f233166756fb20531f88e10eead5fcc245f5a45b5d80067f632eb52d7e78/analysis/1505870284/

Then I googled a lot, and found that the strange domain was related to a ransomware which the name is Rijndael. 

You can check the page for more information of Rijndael here: 
http://www.easyremovemalware.com/tag/rijndael-ransomware-removal-guide

I don't know whether your development environment had been infected or not, but I think I should report it to the developer who can start an investigation on this strange behave of the executable file.

Thanks!

**Comment by lostindark** [comment]
Wasn't able to find ransomware on my dev box. Also tried the virustotal. The default new UI didn't give me that info, while seems the old UI still give that info.

To avoid the potential issue, I moved the build to AppVeyor and the release will be directly published by the build pipeline.
I didn't see the DNS requests anymore. However, 2 engines detected.
https://www.virustotal.com/#/file/3bd027d9b20a6bb8a833814e249630a06e06b4f72459f7f08f12f8cd691127af/detection

Unfortunately VirusTotal didn't provide contact methods for those engines and I can't write email to them asking why it is get flagged.

**Comment by yufeiying** [comment]
Is it possible that some of the components or controls that your project used may be infected in some way? You said that the old UI gave that info. Does it mean that some code of the old UI may not be clean? 

I found a very old post on BleepingComputer, which was posted in 2015, said that a developer who discover that his program has the same behave sending DNS requests. He was also using C#.

Check it out here:
https://www.bleepingcomputer.com/forums/t/572226/just-curious/

**Comment by sylveon** [comment]
Tencent is a chinese antivirus engine. I haven't had any luck getting my own program unflagged by any chinese antivirus. [Here's their support website](http://kf.qq.com). Good luck.

As for SentinelOne, you can use the [contact form](https://www.sentinelone.com/contact/).

Out of curiosity, do you see the same behavior when submitting the original file to [malwr.com](https://malwr.com)?

**Comment by yufeiying** [comment]
Unable to submit the Rapr.exe to Malwr. After the uploading ended, the page showed up an error said that 413 Request Entity Too Large. Even the exe file is 500k.

**Comment by sylveon** [comment]
they seem to be having issues :/

-- 
Envoyé de mon Gmail

**Comment by lostindark** [comment]
Now VirusTotal result seems clean.
For 0.8.4.2:
https://www.virustotal.com/#/file/3bd027d9b20a6bb8a833814e249630a06e06b4f72459f7f08f12f8cd691127af/detection

For latest version 0.9.5:
https://www.virustotal.com/#/file/54ff1cef4b77655d85765faae2aeb8401a46f1ecaf21c72ef1ceddf680f2aa93/detection

Given the build pipeline is now hosted on AppVeyor and I see no place the tool can be affected by malware, I'll close the issue.
