### ISSUE TITLE
Old AMD Radeon drivers are not selected automatically

### ISSUE THREAD

**Issue by OneCrazyRussian** [lostindark/DriverStoreExplorer#27]
If you have more than one AMD Radeon driver installed, the older ones should be selected when "Select Old Drivers" button is pressed, but they are not, unlike all the others
Reproduced on two Win10 systems, 1709 build

They properly differ in both driver version and date (previously some Notebook drivers had their versions bugged, not anymore)

**Comment by AniLeo** [comment]
Can you copy paste the lines of the duplicate drivers? For example:
```
nvmii.inf | Placas gráficas | NVIDIA | 23.21.13.8800 | 12-10-2017 | 450 MB
-- | -- | -- | -- | -- | --
nvmii.inf | Placas gráficas | NVIDIA | 23.21.13.9065 | 03-01-2018 | 442 MB
```
Need to know which other fields are differing. I'd guess they changed ATI to Radeon on Pkg Provider or something like that.

**Comment by OneCrazyRussian** [comment]
Here you go, the notebook set:
c0185923.inf | Видеоадаптеры | Advanced Micro Devices, Inc. | 15.200.1045.0 | 22.06.2015 | 335 MB
c0322096.inf | Видеоадаптеры | Advanced Micro Devices, Inc. | 23.20.15007.1005 | 17.12.2017 | 977 MB
c0322990.inf | Видеоадаптеры | Advanced Micro Devices, Inc. | 23.20.15015.1002 | 12.01.2018 | 977 MB
And the standard desktop line:
c0322990.inf | Видеоадаптеры | Advanced Micro Devices, Inc. | 23.20.15015.1002 | 12.01.2018 | 977 MB

The lines are now the same on notebooks and desktops, unlike older non-crimson ones.

**Comment by AniLeo** [comment]
Well, they change the INF filename so it is not possible to reliably know if they're older drivers or different drivers from the same publisher without adding a per-driver scenarios as far as I'm aware.

**Comment by OneCrazyRussian** [comment]
The inf filename changes in increments though, the latest one has the highest "build number" of sorts

And it's been consistent for few years

**Comment by lostindark** [comment]
The select old driver feature is based on driver class, provider and inf name (a best guess). If any of these changes, we don't know if they're the same drivers or not (we can't make an assumption here). I don't see an easy way of fix this.
