### ISSUE TITLE
Please add the removal of Ghosted devices from the system

### ISSUE THREAD

**Issue by sijo-mathew** [lostindark/DriverStoreExplorer#29]
Is it possible to add support for the removal of ghosted devices from the system. Ghosted devices means, if the device is removed, it will be still shown in the devices manager as hidden device.

Also it will be better to check the driver date along with the driver version. It is just a suggestion. By default stampinf tool will stamp the driver building time as the version in the inf. In this scenario, by using the driver date only we can identify the latest driver.

**Comment by sylveon** [comment]
Deleting ghosted devices can be very dangerous, as it will uninstall
the drivers for any hardware not plugged in right now.

-- 
Envoyé de mon Gmail

**Comment by lostindark** [comment]
DriverStore Explorer currently doesn't read any device information, so it doesn't know which driver is used by which device. This function can not be implemented without a big change.

You can used the Device Cleanup Tool here to remove devices that have been removed.
http://www.uwe-sieber.de/misc_tools_e.html
