### ISSUE TITLE
Crashes if run from network drive and as administrator

### ISSUE THREAD

**Issue by PF4Public** [lostindark/DriverStoreExplorer#31]
Starting from network drive is OK in read-only mode until trying to run with administrative rights -- it crashes then.

**Comment by lostindark** [comment]
Do you have the stack trace?

**Comment by PF4Public** [comment]
It's a typical "application crashed" window. Event log logged the following .NET runtime error:
Application name: Rapr.exe
: System.ArgumentException
   in System.Drawing.Icon.ExtractAssociatedIcon(System.String, Int32)
   in Rapr.DSEForm..ctor()
   in Rapr.Program.Main()

**Comment by lostindark** [comment]
Looks like System.Drawing.Icon.ExtractAssociatedIcon can't handle network path. I'll have a fix soon.

**Comment by lostindark** [comment]
Fixed in df924c9372a5953d636188682114f47dbcdf0a73.
