### ISSUE TITLE
Let DSE remember last window size + position

### ISSUE THREAD

**Issue by pstein** [lostindark/DriverStoreExplorer#33]
As I found out DSE does not remember its last window size and position.

When I close it and later restart it then the main window opens centralized with a small size on screen.
Users have to manually move and resize the window again.
This is tedious and not comfortable.

Can you let DSE remember the last win size+pos in the next release?

thank you

**Comment by lostindark** [comment]
Unfortunately fix DPI issue is hard, especially for Win 7. Currently I have no plan to fix them (not a high pri at this moment).

If anybody want to give it a try, I'm willing to take the PR.
