### ISSUE TITLE
Cannot force delete drivers where the matching PNF file is missing

### ISSUE THREAD

**Issue by parrington** [lostindark/DriverStoreExplorer#35]
I resolved a frustrating problem where four outdated NVIDIA drivers were undeletable, even with force or package delete. Turns out, my oem*.inf files no longer had the matching PNF files. DriverStore Explorer will show the metadata, but list the driver size as 1K.

The fix is to manually delete the corresponding oem* files. I'm not a driver expert, but could the tool handle this type of exception and still clean up the driver instance by removing the specified .inf? To repro this case, just hide the PNF file for a given INF.

**Comment by lostindark** [comment]
This is tricky. If a driver is corrupted, we don't know if the entire folder is gone, or only part of the files are gone. Delete only the oem* files doesn't seem a good idea as it may leave trash behind.
I don't see an reliable way to implement this feature.
