### ISSUE TITLE
HiDPI issue workaround

### ISSUE THREAD

**Issue by FadeMind** [lostindark/DriverStoreExplorer#37]
Please enable in default option in Compatibility tab > DPI settings for Rapr.exe:
![scr-1541882398-001](https://user-images.githubusercontent.com/9846948/48305779-42b33880-e531-11e8-9b36-a98bb8662a51.png)

**Comment by lostindark** [comment]
I've made a fix 136fcb4988336f6a8d5123edbc9f95a4e2881ce1 to see if it can handle HiDPI automatically.
