### ISSUE TITLE
Request: Ability to hide language from language list if language folder is deleted.

### ISSUE THREAD

**Issue by Thdub** [lostindark/DriverStoreExplorer#50]
This is a small request, I don't use all the languages, and would prefer if I delete language folder to hide from the list. 
Actual behavior: if I delete language folder it still shows in list but english is used
Wanted behavior: if I delete  language folder: hide from list.

Ps: can you change français to Français in language list also? with first letter uppercase like in **E**nglish

**Comment by lostindark** [comment]
Fixed uppercase in 93af7e3e433189cf43ceea5229f37c62ab83a6a0.

Language folder detection requires more change and I'll do it later. Ideally I'd only show language that is supported.

**Comment by lostindark** [comment]
I'm thinking just embed the language resource in the main exe (create a single exe). And there won't be ability to remove a support language. How does that sound?

**Comment by lostindark** [comment]
Turns out create single exe that contains all language resource requires a lot of work due to the limitation of resource file handling in msbuild.
Instead, I've implement this request in 9f66a2cccd50e688e97537348e8e31a0f8b9790b.
