### ISSUE TITLE
Remember UI settings follow-up

### ISSUE THREAD

**Issue by Thdub** [lostindark/DriverStoreExplorer#54]
Not a big issue, but still doesn't remember "column size": when re-opening RAPR, it automatically "fits to content size". That's great...however if "column title" is longer than "colum content", end part of the title is hidden.

Actual behavior (fits to content)
![1](https://user-images.githubusercontent.com/37347541/49076121-995e8900-f238-11e8-8ac4-bd26092aceb9.JPG)

Desired behavior (fit to title) 
![2](https://user-images.githubusercontent.com/37347541/49076135-9ebbd380-f238-11e8-8ab1-147932546bb4.jpg)

Or, otherwise (3rd option), do not fit to size but re-open with exact same "column size" as it left: small, or very big, if I want. But I personally prefer "fit to title" behavior.

Ps: Another option/quickest fix, you keep "fit to content" behavior but get rid of "driver"/"du pilote" words, leaving only  Date/Version in the title instead (same words in french and english), that way title is smaller than content and its end isn't hidden.
But thinking now, it's surely better to keep "Driver" word in the title: remove the word could confuse the user between "install date" and "driver date" (I wouldn't be sure myself which date it is otherwise)

Ps2: Wow, that just took me to another idea/request (sorry...) Maybe you could add an "installation date" column? Or else, wouldn't it be great to "highlight" installed driver? (I like this one...) 
Like this, the user is confident about which driver he can delete (=the ones "not in use", for example).
Another (random) idea would be to add a button to "select unused drivers" .

**Comment by lostindark** [comment]
Unfortunately, read driver installation date is not trivial. Haven't figure out what API I can use.

I'll see what I can do with column size.

**Comment by lostindark** [comment]
Fixed column size with fff17f0f9db202261c21662b525fd62595e8f330.

**Comment by Thdub** [comment]
What about "highlight" installed drivers ? 
And possibility to "select" installed/highlighted driver ?
This may be easier than read installation date?

**Comment by lostindark** [comment]
Unfortunately that requires DISM API also. So not a simple change.

**Comment by lostindark** [comment]
I'm close this issue as the UI part is solved. Feel free to open new issues for new functionality (driver installation date, highlight installed drivers etc).
