### ISSUE TITLE
Can't Force Delete (No checkbox)

### ISSUE THREAD

**Issue by Leighton-Cyr** [lostindark/DriverStoreExplorer#57]
When I try to delete old drivers, I get an error message. The previous release had a checkbox to allow a forced delete. In release 0.10.3 there is no checkbox so I can't delete the old driver. Had to revert to 0.9.39 in order to delete old drivers.

**Comment by lostindark** [comment]
Fixed in b3223b7de23be1899473d370889d23d8b5d32d11
