### ISSUE TITLE
"Select Old" Context Menu Item is Needed

### ISSUE THREAD

**Issue by hl2guide** [lostindark/DriverStoreExplorer#6]
A "Select Old" Context Menu Item is needed for this program to be really useful (maybe even a button on the right side under "Operations" Group Box?). 

The function should be to select all checkboxes of items with duplicated names (INF column) and the "Driver Date" is old.

**Comment by lostindark** [comment]
Implemented in commit e0886fb7d6797f7ac72b39e24d910e8ffe94ad02
