### ISSUE TITLE
Select Old Drivers does not works

### ISSUE THREAD

**Issue by FadeMind** [lostindark/DriverStoreExplorer#60]
Hi, Option Select Old Drivers does not works at all since `0.10.13`
Works well in 0.10.10 and older.

**Comment by lostindark** [comment]
Do you have a screenshot on the list of drivers that should be considered as old drivers?

**Comment by FadeMind** [comment]
This consider all old drivers. No matter what category or sorting I do. Current list (0.10.10) without duplicates:

![s](https://i.imgur.com/R6ejOfa.png)
![d](https://i.imgur.com/1PkYN6t.png)

Device sample list with second older LAN driver in Driver Store. 

![g](https://i.imgur.com/c3XD1Tj.png)

**Comment by lostindark** [comment]
Wasn't able to get a repro or figure out what happened yet.
Can you try 0.10.15 to export your driver list as csv and attach the result here?

**Comment by FadeMind** [comment]
CSV: https://pastebin.com/raw/nAZKPcf5

**Comment by lostindark** [comment]
Given the latest works, I'm close this.
