### ISSUE TITLE
Expand devices list

### ISSUE THREAD

**Issue by Hunter23071985** [lostindark/DriverStoreExplorer#61]
Hello!

Very convenient program, but it doesn't detect many files in my driver store folder.
I don’t see standard MS drivers, my HDD, SSD, CD-ROM, phone, virtual PDF-Xchange printer, etc.
Also I don't see devices for which drivers are not installed.
In total only 44 rows against 454 rows in [DevManView](https://www.nirsoft.net/utils/device_manager_view.html)...

My request:
1. Expand devices list.
2. Add the total number and size in the status bar.
3. Highlight devices for which drivers are not installed.

Thank you!

**Comment by sylveon** [comment]
DevManView and DriverStore Explorer serve a different purpose.

DriverStore Explorer is to view the Windows driver store, which is where Windows stores third-party drivers. Neither built-in Microsoft drivers nor missing drivers are located in the driver store.

DevManView a tool to view the currently connected devices and their attached (or lack of) driver. As such, you won't be able to see for example drivers present in the driver store but not attached to any existing device.

**Comment by lostindark** [comment]
Thanks @sylveon for explanation. That what I wanted to say.

**Comment by Hunter23071985** [comment]
Guis, it's not difficult to calc:
1642 Mb - the size of drivers in C:\Windows\System32\DriverStore\FileRepository
1405 Mb - the size of drivers in DriverStore Explorer
0237 Mb - where is 14% of the storage?
Database: https://drive.google.com/file/d/1SHCvnNSJ93LsPCpx01ggZwwnL4JPLEKX/view?usp=sharing.
