### ISSUE TITLE
Code analysis?

### ISSUE THREAD

**Issue by ariccio** [lostindark/DriverStoreExplorer#64]
First: I love this little tool, fyi.

Have you ever considered using code analysis or the [`.NET compiler platform analyzers`](https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-analyzers?view=vs-2019)? As a curious native developer, I ran Visual Studio 2019's built in code analysis (which is apparently depreciated for .NET 🤷) and while there's lots of noise (spelling issues, etc...) it does look like there's some interesting issues with exceptions, datatype mismatches, and weird language problems.

I tried it with `Microsoft All Rules` at first and got 302 warnings (again, lots of noise), and then the `Microsoft Managed Recommended Rules`, which only produced 7 warnings, of which only two look actually interesting to me, missing lots of other things. You might want to just use the All Rules preset, and then manually ignore the most common two or three warnings.

**Comment by lostindark** [comment]
Tried latest fxcop and didn't find anything that is critical.
I've fixed a few issues and will get to the rest when I got a chance.

**Comment by lostindark** [comment]
Fixed in 177062ea9a8f27f2ee4125bd571a107671ba0cb3.
