### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mrkaban** [lostindark/DriverStoreExplorer#66]
Hello, thanks for the program! I added it to my site in Russian about free software ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%83%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D1%8B/%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0/driverstore-explorer.html)).

I wanted to clarify once again, is the program really distributed under the gnu gpl license? If yes, please indicate the license in the About menu.

**Comment by lostindark** [comment]
Yes it's GPL. I've updated the about.
