### ISSUE TITLE
DriverStoreExplorer.v0.10.28, doesn't work in Windows 7.

### ISSUE THREAD

**Issue by gdgsdg123** [lostindark/DriverStoreExplorer#69]
DriverStoreExplorer.v0.10.28, doesn't work in Windows 7.
![0](https://user-images.githubusercontent.com/33557593/59136083-2c465180-8947-11e9-87ea-f4732ef86c06.png)

DriverStoreExplorer.v0.10.15 works OK.
![1](https://user-images.githubusercontent.com/33557593/59136092-349e8c80-8947-11e9-820f-cc5f61afab1c.png)

**Comment by lostindark** [comment]
Looks like it can't find DismApi.dll. Can you try to search this dll in System drive?

**Comment by DrFeelNice** [comment]
Same issue for me !
DismApi.dll exists, but probably your software can't find it in the right place and/or in the registry !?

**Comment by lostindark** [comment]
Can you share the DLL location in your system?

**Comment by DrFeelNice** [comment]
2 of my 4 Win7Pro64 PC's have this problem but with only one location, the first of my preceding screenshot, I mean:
C:\Windows\winsxs\amd64_microsoft-windows-a..xperience-inventory_31bf3856ad364e35_6.1.7601.18944_none_e84f166fe58f01d3\

**Comment by gdgsdg123** [comment]
Cannot find "DismApi.dll".

Windows 7 Ultimate (SP1, x64).

**Comment by lostindark** [comment]
Seems DismApi only gets install if some Win 7 kb gets installed. I didn't find an easy way to get DismApi install to Win7.
I've made a change to fall back to pnputil if Dism is not available. Chang here: a3d1f386802d36e9de07784a568e8669e44a225c.
