### ISSUE TITLE
Program icon would be nice

### ISSUE THREAD

**Issue by hl2guide** [lostindark/DriverStoreExplorer#7]
A program icon would be nice to add (top left) 👯 :dancing_men:

**Comment by lostindark** [comment]
OK. The question is where to find a good icon.

**Comment by hl2guide** [comment]
How about:
http://findicons.com/icon/591920/administrative_tools
OR
http://findicons.com/icon/85440/tools

you could use them as long as you attribute them.

**Comment by lostindark** [comment]
Unfortunately both icon don't look good (in title or task bar).

**Comment by ltGuillaume** [comment]
The Multi-res ICO of http://findicons.com/icon/591920/administrative_tools looks great to me, even 16x16 pixels.

**Comment by lostindark** [comment]
Unfortunately the icon above doesn't look good with taskbar highlight.
I'm considering use this one: http://findicons.com/icon/60947/developer_alternate.

**Comment by ltGuillaume** [comment]
Seems nice

**Comment by ltGuillaume** [comment]
Seems nice, but the 16x16 variant is quite ugly :P

**Comment by ltGuillaume** [comment]
16px variant of that one is quite ugly imho. Maybe this one, where you can tinker arount with the grey value as much as you want :P http://www.iconskid.com/showing-gallery-for-business-system-icon-icon-103251.html

**Comment by lostindark** [comment]
I played with this icon (http://www.iconskid.com/showing-gallery-for-business-system-icon-icon-103251.html) a little bit with GIMP and IcoFX, and checked in a modified version 57dfe400242310cdfa34ba0c7032f97a06a60e64

**Comment by ltGuillaume** [comment]
Cool!
