### ISSUE TITLE
About not working

### ISSUE THREAD

**Issue by DrFeelNice** [lostindark/DriverStoreExplorer#70]
About doesn't work properly (on Win7Pro64) !
The last v0.10.28 doesn't check the Internet access (my Windows firewall was not open to DSE).
No problem when my firewall is open to DSE.

![2019-06-08_133427](https://user-images.githubusercontent.com/51505681/59146779-a4b61c80-89f2-11e9-9133-27e1cdbe5394.png)

**Comment by lostindark** [comment]
Fixed in 689403c0c3968a27f64f2b50a4915be66b08a7fa.
