### ISSUE TITLE
Path2 error

### ISSUE THREAD

**Issue by DrFeelNice** [lostindark/DriverStoreExplorer#75]
DSE v0.10.35 can't start on Win7Pro64 :

![2019-06-11_174300](https://user-images.githubusercontent.com/51505681/59287326-b6f1be00-8c71-11e9-8f83-f376f135b238.png)

`2019-06-11 16:19:58Z [Error]: System.ArgumentNullException: La valeur ne peut pas Ãªtre null.
Nom du paramÃ¨treÂ : path2
   Ã  System.IO.Path.Combine(String path1, String path2)
   Ã  Rapr.Utils.DriverStoreRepository.GetSystemRootInfContent(String infName) dans C:\projects\driverstoreexplorer\Rapr\Utils\DriverStoreRepository.cs:ligne 122
   Ã  Rapr.Utils.DriverStoreRepository.FindInfInfo(String infName, String& originalInfName, String& driverFolderLocation, Int64& estimateSize) dans C:\projects\driverstoreexplorer\Rapr\Utils\DriverStoreRepository.cs:ligne 39
   Ã  Rapr.Utils.PnpUtil.EnumeratePackages() dans C:\projects\driverstoreexplorer\Rapr\Utils\PnpUtil.cs:ligne 69
   Ã  Rapr.DSEForm.BackgroundWorker1_DoWork(Object sender, DoWorkEventArgs e) dans C:\projects\driverstoreexplorer\Rapr\DSEForm.cs:ligne 366
   Ã  System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   Ã  System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
`

**Comment by lostindark** [comment]
Looks like on entry in pnputil output can't be parsed. Can you run the following command and paste the output here?
pnputil /e

**Comment by DrFeelNice** [comment]
Here it is:

[save.txt](https://github.com/lostindark/DriverStoreExplorer/files/3277888/save.txt)

**Comment by lostindark** [comment]
Can you try v0.10.15 and see if that works?

**Comment by DrFeelNice** [comment]
v0.10.15 works fine, it's the best !
I reuse it instead of v0.10.28 et v0.10.35...

**Comment by lostindark** [comment]
Fixed in 985aef05eb85a587992e927aaf218e4bfe722abe.
You can try v0.10.39 now.

**Comment by DrFeelNice** [comment]
Works fine now, thanks !
