### ISSUE TITLE
Still doesn't work on WIndows 7 (latest version)

### ISSUE THREAD

**Issue by LocutusX** [lostindark/DriverStoreExplorer#76]
0.10.39 still doesn't work on Windows 7.

need to fallback to an older version to get it to work.

**Comment by lostindark** [comment]
Can you share screenshot and log file if exists? Also, can you share pnputil /e output? Thanks.

**Comment by DrFeelNice** [comment]
v0.10.39 works fine on my 4 PC's (Win 7 Pro 64) + 2 Laptops (Win 7 Home 64 and Win 7 Pro 32) !

**Comment by lostindark** [comment]
The recent version requires .net framework 4.5 (up from .net 4.0). Make sure you have .net framework 4.5 or later installed.

Please share detail error information, or else I don't have a way to troubleshoot this issue.

**Comment by aurelbdx** [comment]
Same problem for me on Windows 7 x64 since v0.10.21
with v0.10.21 I can see only few drivers on the list:
https://www.dropbox.com/s/el3t1x7ypa6kdxg/1.JPG?dl=0
with vv0.10.15 no problem
https://www.dropbox.com/s/b6tcexrzd5yujq0/2.JPG?dl=0

**Comment by lostindark** [comment]
@aurelbdx can you upload the log file?

**Comment by aurelbdx** [comment]
I have these lines in the log file:
2019-07-09 02:32:30Z [Information]: ---------------------------------------------------------------
2019-07-09 02:32:30Z [Information]: Rapr started
2019-07-09 02:34:19Z [Information]: Shutting down - reason UserClosing
2019-07-09 20:25:42Z [Information]: ---------------------------------------------------------------
2019-07-09 20:25:42Z [Information]: Rapr started
2019-07-09 20:26:05Z [Information]: Prêt

**Comment by lostindark** [comment]
@aurelbdx can you run the following command and paste the results?
dism /online /get-drivers
pnputil /e

**Comment by aurelbdx** [comment]
With dism /online /get-drivers:
https://www.dropbox.com/s/4495k71du21gx2l/dism%20online%20get-drivers.txt?dl=0
with pnputil /e:
https://www.dropbox.com/s/vyok3xy23s9fgkb/pnputil%20e.txt?dl=0

**Comment by lostindark** [comment]
@aurelbdx for you case looks like DISM has an issue on your system. I don't have a good way to fix that.
I'll consider add an option to allow choose from DISM or pnputil.

**Comment by aurelbdx** [comment]
OK thanks :)

**Comment by DrFeelNice** [comment]
Hi Teddy,
No problem at all on my 6 Win7 PC's with the v0.10.43 !

**Comment by dinkope** [comment]
I've got exactly the same problem with my Win7x64 - RAPR works with PnPUtil but not with DISM. So obviously  **@aurelbdx** is not alone, as is **LocutusX** and many others... An option to select either would be nice.

And WTH could be wrong with DISM on some Win7 systems but not on others ?!?

**Comment by lostindark** [comment]
@aurelbdx @dinkope Are your Win7 systems update to date (with all available updates installed)?
What is your DISM version?

My only guess is some DISM maybe buggy. However, install the latest DISM is tricky as you'll need to install WDK.

**Comment by aurelbdx** [comment]
Yes, all available updates are installed.

C:\Windows\system32>dism /?
Deployment Image Servicing and Management tool
Version: 6.1.7601.24499

**Comment by dinkope** [comment]
My updates are also up to date. However my DISM is not that new as **@aurelbdx**'s.

C:\>dism /?
Deployment Image Servicing and Management tool
Version: 6.1.7600.16385

**Comment by lostindark** [comment]
Given DISM seems buggy on Win 7, I've switch to use pnputil on Win 7 in v0.10.51.
Originally I was thinking give this as an option, however, it seems there is no need to use DISM on Win 7.

**Comment by aurelbdx** [comment]
Windows 7 support will end on January 14, 2020 so it's time for me to go to windows 10 but thanks anyway :)
