### ISSUE TITLE
Error: The request is not supported

### ISSUE THREAD

**Issue by neopack1** [lostindark/DriverStoreExplorer#86]
Error in all versions after v0.10.15 
Error msg: **"The request is not supported"** 

Windows 10 x64 Pro Insider Preview (10.0.18936.1000)

![rapr_error_0001](https://user-images.githubusercontent.com/14898202/62241551-a7713480-b3d9-11e9-98c3-671d1399cfdd.jpg)

**Comment by lostindark** [comment]
Can you share the log?

**Comment by lostindark** [comment]
Tested the latest version on Win 10 18950.1000 and no repro so far.

**Comment by lostindark** [comment]
No repro on 18956 as well.
Please reopen the issue if you found a repro on latest version and attach logs.
