### ISSUE TITLE
anomaly

### ISSUE THREAD

**Issue by FadeMind** [lostindark/DriverStoreExplorer#88]
![s](https://i.imgur.com/epVo9mV.png)

**Comment by lostindark** [comment]
Currently, the device name and driver files are match by the oemxxx.inf. In some case, the driver of the device is pointing to a wrong oemxxx.inf file. Maybe the oemxxx.inf was the right inf file for the device. And then it gets deleted, and a new driver for different device is installed and use the same oemxxx.inf name.

Unfortunately it seems a problem on how windows managed the oemxxx.inf file, and there is no easy fix for this issue.

A potential way is to move to use Windows Driver Store API, which can obain more information about drivers installed in driver store, so we can have a better match. However, the driver store API is private, no public information available.

**Comment by FadeMind** [comment]
@lostindark  thank you for clarification. Regards.

**Comment by lostindark** [comment]
I added additional driver date+version check in 1e28ff63b8cafb32d01942278c5567a04995290e, which should prevent this from happening.
