### ISSUE TITLE
AppData to clean-up...

### ISSUE THREAD

**Issue by DrFeelNice** [lostindark/DriverStoreExplorer#89]
Hi Teddy,

I've found a lot of useless data (coming from old versions) into C:\"Users"\"Username"\AppData\Local\Rapr\Rapr.exe_Url_hmq0zv33s133i1iv4vpqqsys2vivlhkh\ !
Could you clean that up in the next version ?

Regards,

**Comment by lostindark** [comment]
Fixed in 138885c7beaab3189bd6b86b79207448ca603ec2.
