### ISSUE TITLE
Request:Portable

### ISSUE THREAD

**Issue by sick13** [lostindark/DriverStoreExplorer#90]
can you make the program store config,log etc files where the *.exe is for true portability

as of now it stores some files in AppData

**Comment by lostindark** [comment]
I've already moved the log file to the program folder, but the config file is a little bit tricky.
Some config are per machine (like window location etc), which should not go with the exe.

**Comment by sick13** [comment]
ok got it, don't know how the program works so it was just a suggestion
thx for looking into this
