### ISSUE TITLE
DriverStoreExplorer Deletes in use drivers without selecting "Force Deletion"

### ISSUE THREAD

**Issue by hsehestedt** [lostindark/DriverStoreExplorer#92]
Windows 10 1909 64-Bit
RAPR 0.10.58.0

If I select all drivers on my system and then select "Delete Driver" WITHOUT "Force Deletion" selected, for some reason Driver Store Explorer is still deleting two drivers that are in use.

The first of these shows up under the category "FS HSM filters" and is called "gameflt.inf" with a provider of "Xbox". I'm uncertain what effect the removal of this driver has.

The second driver, which is more of a concern to me, is called "hellofacemigration.inf" under the "Biometric devices" category. The deletion of this driver has the effect that Windows Hello will no longer work with my camera.

To remedy the situation, I need to manually reinstall the driver for my camera, then, within device manager I need to scan for changes, and then reboot. The hellofacemigration.inf will then be back and all is operating normally. Incidentally, the "gameflt.inf" will also be back at this point.

Why is Driver Store Explorer seemingly not determining that these drivers are in use by the system?

**Comment by lostindark** [comment]
Is there devices associated with these 2 drivers?

**Comment by hsehestedt** [comment]
Yes,. As I noted in my original post, the "hellofacemigration.inf" is used for facial recognition using the camera in the laptop. I'm not clear on what the other one, the "gameflt.inf" with a provider of "Xbox" affects.

**Comment by lostindark** [comment]
Does DriverStoreExplorer show device name for "hellofacemigration.inf"?
For "gameflt.inf", unfortunately there is no device associated with it, so DriverStoreExplorer will just delete it if you select delete.

**Comment by hsehestedt** [comment]
Since I submitted the problem report a new driver has become available for the camera on my laptop and that has been installed. When I run Driver Store Explorer now, I no longer see an INF called hellofacemigration.inf but I do see a helloface.inf. That driver is listed as a Biometric device with "Windows Hello Face" as the provider. The Device Name is listed as "Windows Hello Face Software Device".

I'm going to try running Driver Store Explorer and deleting drivers again later today on my laptop - I can't do so right now as I am in the middle of something at this time. I will report back later if I am still seeing any difficulty or not.

**Comment by hsehestedt** [comment]
I had a chance to try this a bit earlier than I had thought I would and I had no difficulties this time.

There are some differences: This time I am on Windows 10 version 2004 and as I noted before, a new camera driver was automatically installed by Windows update on the system.

Since I can no longer duplicate the issue I guess that you can just close out the issue at this time.

Thanks for responding to this issue.
