### ISSUE TITLE
Exporting the driver list as CSV using French should use the semicolon delimiter instead of commas.

### ISSUE THREAD

**Issue by VinnyVynce** [lostindark/DriverStoreExplorer#93]
Hi, as the title says, the default delimiter for french operating systems in the CSV format is a semicolon instead of a comma. The CSV files exported are pointless for any french speaker unless you change the delimiter system wide which you don't want to in most cases.
Thanks!

**Comment by lostindark** [comment]
Fixed in 430767410fb0a6163f830c2488394097ee08011b.
You can try a private build here:
https://ci.appveyor.com/api/buildjobs/de9tbq8pxwsjobai/artifacts/Rapr%2Fbin%2FDriverStoreExplorer.v0.10.61.zip

**Comment by VinnyVynce** [comment]
Hi @lostindark, the delimiters work flawlessly! Another thing to maybe change, idk if you save the CSV with UTF8 encoding or not but the driver classes have encoding issues.

PÃ©riphÃ©riques USB should be P**é**riph**é**riques USB
Lecteurs de cartes Ã  puce should be Lecteurs de cartes **à** puce
PÃ©riphÃ©riques   systÃ¨me should be P**é**riph**é**riques syst**è**me.

**Comment by lostindark** [comment]
Now the tool export as UTF8.
Private build: https://ci.appveyor.com/api/buildjobs/bqbeqvkbjlrhsl61/artifacts/Rapr%2Fbin%2FDriverStoreExplorer.v0.10.62.zip
