### ISSUE TITLE
Drivers deleted or also uninstalled?

### ISSUE THREAD

**Issue by drMaGo** [lostindark/DriverStoreExplorer#96]
Hi!

First of all, lat me thank you for the DriverStoreExplorer app.

Does the program only remove driver files from the Windows Drvier Store or does it also uninstall these drivers and delete associated registry entries? I am not very familiar with this subject. If the driver is not used by any device, does it mean that it is installed?

Best regards
Matt

**Comment by lostindark** [comment]
When you try delete a driver in driver store explorer, if it is used by a device currently, the deletion will fail unless you choose force delete. Force delete will uninstall the driver from the device (include the registry), and remove the driver.

If the driver is not been used, delete it will remove the files from driver store.
