### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by KovalevArtem** [lostindark/DriverStoreExplorer#97]
It is sad that the program is only in English - I propose to translate.
I am ready to help in the translation into Russian.
(For example, you can use Weblate, Crowdin, or any other service. Free for open source projects.)

**Comment by lostindark** [comment]
It supports multi languages including russian.

**Comment by KovalevArtem** [comment]
Oops

**Comment by comradekingu** [comment]
+1 for Weblate. (Crowdin isn't, and is closed source.)
